

import { MenuItem } from "primeng/api/menuitem";

export const ACCOUNT_OPTIONS = [
  {
    MENU: {
      dashboard: [] as MenuItem[],
      report: [
        {
          code: 'summaryReport',
          label: 'Quản lý chuyên đề',
          icon: 'pi pi-chart-bar',
          sort: 1,
          routerLink: '/reports/summary-report',
          parentCode: null,
          position: 2,
          actions: '{"view": false, "export": false}',
          queryParams: {},
          status: 1,
        },
      ],
      main: [
        {
          code: 'posts',
          label: 'Quản lý tin bài',
          icon: 'pi pi-book',
          sort: 3,
          routerLink: '/posts',
          parentCode: null,
          position: 1,
          actions: '{"view": false}',
          queryParams: {},
          status: 1,
        },
      ],
      setting: [] as MenuItem[],
    },
    ROLES: {
      posts: {
        view: true,
      },
      summaryReport: {
        view: true,
        export: true,
      },
      topic: {
        view: true,
        add: true,
        update: true,
        delete: true,
        copy: true,
        export: true,
      },
      emportReport: {
        view: true,
        add: true,
        update: true,
        delete: true,
        copy: true,
        export: true,
      },
      userManager: {},
    },
    URLS: ['/posts', '/reports/summary-report', '/emport-report', '/setting'],
  },
  {
    MENU: {
      dashboard: [] as MenuItem[],
      report: [
        {
          code: 'summaryReport',
          label: 'Quản lý chuyên đề',
          icon: 'pi pi-chart-bar',
          sort: 1,
          routerLink: '/reports/summary-report',
          parentCode: null,
          position: 2,
          actions: '{"view": false, "export": false}',
          queryParams: {},
          status: 1,
        },
        {
          code: 'mentions',
          label: 'Số lượng đề cập',
          icon: 'bi bi-sort-numeric-up-alt',
          sort: 2,
          routerLink: '/reports/mentions',
          parentCode: null,
          position: 2,
          actions: '{"view": false, "export": false}',
          queryParams: {},
          status: 1,
        },
        {
          code: 'sentiment',
          label: 'Sắc thái bài viết',
          icon: 'bi bi-hand-thumbs-up',
          sort: 3,
          routerLink: '/reports/sentiment',
          parentCode: null,
          position: 2,
          actions: '{"view": false, "export": false}',
          queryParams: {},
          status: 1,
        },
        {
          code: 'ranking',
          label: 'Bảng xếp hạng',
          icon: 'bi bi-sort-up',
          sort: 4,
          routerLink: '/reports/ranking',
          parentCode: null,
          position: 2,
          actions: '{"view": false, "export": false}',
          queryParams: {},
          status: 1,
        },
      ],
      main: [
        {
          code: 'posts',
          label: 'Quản lý tin bài',
          icon: 'pi pi-book',
          sort: 3,
          routerLink: '/posts',
          parentCode: null,
          position: 1,
          actions: '{"view": false}',
          queryParams: {},
          status: 1,
        },
        {
          code: 'topic',
          label: 'Quản lý chuyên đề',
          icon: 'pi pi-chart-pie',
          sort: 4,
          routerLink: '/social-topic',
          parentCode: null,
          position: 1,
          actions: '{"view": false, "add": false,"update":false, "delete": false, "copy": false, "export": false}',
          queryParams: {},
          status: 1,
        },
        {
          code: 'notification',
          label: 'Quản lý cảnh báo',
          icon: 'bi bi-alarm',
          sort: 6,
          routerLink: null,
          parentCode: null,
          position: 1,
          actions: null,
          queryParams: {},
          status: 1,
          items: [
            {
              code: 'ntfApp',
              label: 'Cảnh báo qua notification',
              icon: null,
              sort: 61,
              routerLink: '/notification/ntf-app',
              parentCode: 'notification',
              position: 1,
              actions: '{"view": false}',
              queryParams: '{ "type": 1 }',
              status: 1,
            },
            {
              code: 'ntfEmail',
              label: 'Cảnh báo qua email',
              icon: null,
              sort: 62,
              routerLink: '/notification/ntf-email',
              parentCode: 'notification',
              position: 1,
              actions: '{"view": false}',
              queryParams: '{ "type": 2 }',
              status: 1,
            },
            {
              code: 'ntfConfig',
              label: 'Tùy chỉnh cảnh báo',
              icon: null,
              sort: 63,
              routerLink: '/notification/ntf-config',
              parentCode: 'notification',
              position: 1,
              actions: '{"view": false, "add":false, "delete":false, "update":false}',
              queryParams: {},
              status: 1,
            },
            {
              code: 'ntfTopic',
              label: 'Duyệt tùy chỉnh cảnh báo',
              icon: null,
              sort: 64,
              routerLink: '/notification/ntf-topic',
              parentCode: 'notification',
              position: 1,
              actions: '{"view": false, "approve":false}',
              queryParams: {},
              status: 1,
            },
          ],
        },
      ],
      setting: [
        {
          code: 'userManager',
          label: 'Quản lý người dùng',
          icon: 'bi bi-person-circle',
          sort: 1,
          routerLink: null,
          parentCode: null,
          position: 3,
          actions: null,
          queryParams: {},
          status: 1,
          items: [
            {
              code: 'account',
              label: 'Quản lý tài khoản',
              icon: null,
              sort: 13,
              routerLink: '/account',
              parentCode: 'userManager',
              position: 3,
              actions: '{"view": false,"add": false,"update": false,"delete": false,"approve":false}',
              queryParams: {},
              status: 1,
            },
          ],
        },
      ],
    },
    ROLES: {
      posts: {
        view: true,
      },
      topic: {
        view: true,
        add: true,
        update: true,
        delete: true,
        copy: true,
        export: true,
      },
      notification: {},
      ntfApp: {
        view: true,
      },
      ntfEmail: {
        view: true,
      },
      ntfConfig: {
        view: true,
        add: true,
        delete: true,
        update: true,
      },
      ntfTopic: {
        view: true,
        approve: true,
      },
      summaryReport: {
        view: true,
        export: true,
      },
      mentions: {
        view: true,
        export: true,
      },
      sentiment: {
        view: true,
        export: true,
      },
      ranking: {
        view: true,
        export: true,
      },
      userManager: {},
      account: {
        view: true,
        add: true,
        update: true,
        delete: true,
        approve: true,
      },
    },
    URLS: [
      '/posts',
      '/social-topic',
      '',
      '/notification/ntf-app',
      '/notification/ntf-email',
      '/notification/ntf-config',
      '/notification/ntf-topic',
      '/reports/summary-report',
      '/reports/mentions',
      '/reports/sentiment',
      '/reports/ranking',
      '/account',
    ],
  },
];


export const ROLE_MENU = [
  { ACCOUNT_OPTIONS: ACCOUNT_OPTIONS[0] },
  { ACCOUNT_OPTIONS: ACCOUNT_OPTIONS[1] }
]
